# Generated by Django 4.1.3 on 2022-12-24 20:13

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=student.models.generate_next_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rollNumber', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=2)),
                ('img', models.ImageField(upload_to=student.models.student_img_path)),
                ('encodings', models.BinaryField()),
            ],
        ),
    ]
