# Generated by Django 4.1.3 on 2022-12-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='encodings',
        ),
    ]
