# Generated by Django 4.1.3 on 2022-12-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_encodings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='encodings',
            field=models.BinaryField(default=None),
        ),
    ]
