# Generated by Django 4.1.3 on 2023-03-03 09:07

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(default=teacher.models.generate_next_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to=teacher.models.teacher_img_path)),
                ('encodings', models.CharField(default=None, max_length=5000, null=True)),
            ],
        ),
    ]
